- name: Instalação dos packages
  apt:
    name: "{{ ubuntu.packages }}"
    state: present
    update_cache: yes

- name: SO Upgrade (apt-get full-upgrade)
  apt:
    upgrade: full
    autoremove: yes
    autoclean: yes

- name: Configuração do docker
  block:
    - name: Adição da chave do docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Registro de Versão do ubuntu
      command: lsb_release -cs
      register: ubuntu_version
      changed_when: False
    
    - name: Nome da versão do ubuntu  
      debug:
        msg: "{{ ubuntu_version.stdout }}"

    - name: Adiciona o repositorio do docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: Instalação do Docker
      apt:
        package: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

    - name: Configura usuário base do docker
      user:
        name: "{{ usuario_default }}"
        state: present
        group: docker
      
    - name: Cria Pasta de configuração do docker
      file:
        state: directory
        path: /etc/docker
        mode: 0644

    - name: Configuração do Systemd para Docker
      copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
        mode: 0644      
      notify:
        - Habilita DockerD

- name: Configuração do Kubernetes
  block:
    - name: Cria arquivos do sysctl.d & modules-load.d config
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0644
      loop:
        - /etc/modules-load.d/
        - /etc/sysctl.d/
      changed_when: False

    - name: Configuração de Module Kernel
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          br_netfilter
          overlay

    - name: Configuração de Sysctl
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1


- name: Instalação da ferramenta Kube
  block:
    - name: Adicione k8s keys
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Instalação dos modulos k8s
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Instalação dos packages k8s 
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl
  when: package.enabled
    
